AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  UrlShortenerApiApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api.yaml

  UrlShortenerDatabaseApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./database.yaml

  UrlShortenerLambdaApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambda.yaml
      Parameters:
        SecretArn: !GetAtt UrlShortenerDatabaseApplication.Outputs.SecretArn
        Address: !GetAtt UrlShortenerDatabaseApplication.Outputs.Address
        Port: !GetAtt UrlShortenerDatabaseApplication.Outputs.Port
    DependsOn:
      - UrlShortenerApiApplication
